import { Metadata } from "next";
import { ViewResumen } from "@/views";

export const metadata: Metadata = {
  title: "RIMAC Seguros - Resumen",
  description: "Generated by create next app",
};


export default function PageResumen() {
  return <ViewResumen />
}

