import { Metadata } from "next";
import { ViewHome } from "@/views";

export const metadata: Metadata = {
  title: "RIMAC Seguros",
  description: "Generated by create next app",
};


export default function PageHome() {
  return <ViewHome />
}

