import { Metadata } from "next";
import { ViewPlanCobertura } from "@/views";

export const metadata: Metadata = {
  title: "RIMAC Seguros - Plan Cobertura",
  description: "Generated by create next app",
};

export default function PagePlanesCobertura() {
  return <ViewPlanCobertura />
}
